# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Belay < Formula
  desc "AI-aware local version control for concurrent agent workflows"
  homepage "https://github.com/davidparkercodes/belay"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidparkercodes/belay/releases/download/v1.0.0/belay_1.0.0_darwin_amd64.tar.gz"
      sha256 "462367bf29532447d26202ffa4568ece50da8ae47c0ddc15873ba3c9ef8ae649"

      define_method(:install) do
        bin.install "belay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidparkercodes/belay/releases/download/v1.0.0/belay_1.0.0_darwin_arm64.tar.gz"
      sha256 "195eca4c582f8727ed4894ca61bb7710c16a52bb1d986b9fadbcfdfae8598a6e"

      define_method(:install) do
        bin.install "belay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidparkercodes/belay/releases/download/v1.0.0/belay_1.0.0_linux_amd64.tar.gz"
      sha256 "9fded16dead1eb523faafe48486b494ba5f10d2c5b7dc2cc5fbbf196d311d964"
      define_method(:install) do
        bin.install "belay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidparkercodes/belay/releases/download/v1.0.0/belay_1.0.0_linux_arm64.tar.gz"
      sha256 "2c26076b0957ba69c3719685588a8416c9f973b2ea5184b87efb3efd7eef80ef"
      define_method(:install) do
        bin.install "belay"
      end
    end
  end

  test do
    system "#{bin}/belay", "--version"
  end
end
