# This file was generated by GoReleaser. DO NOT EDIT.
cask "belay" do
  version "1.7.2"

  on_macos do
    on_arm do
      sha256 "b959f26a2ab6a38e9066ac5a995dc5d7353dc74f10b3e0bba923bfe1f4fe33f1"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c8d0db4f78ad4950dfb8c2f10e98d7fc89e460dad1ec35b322c187670809f05d"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "98f52e0abd704dd2a8c4809e1085deaa04c276571717a3418dc15766f783b114"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d3e6d80dd3cd007d3a06811b7bd0f009e7e022de54b4ded41a492483d48b4e0e"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "belay"
  desc "AI-aware local version control for concurrent agent workflows"
  homepage "https://github.com/davidparkercodes/belay"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "belay"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/belay"]
    end
  end

  # No zap stanza required
end
