# This file was generated by GoReleaser. DO NOT EDIT.
cask "belay" do
  version "1.7.0"

  on_macos do
    on_arm do
      sha256 "602f2d99a030fa92459d2e1cea5ac41717907cf7b9f540b1595f21ad6d37998b"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a395363ae2d86a3ce65bb9328d9da2da52c0dd17f1d81efb8b49cf7c4dca3a84"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a0e5cc1b7c84a80dd41472b261dee0678809c039db862f8acee3d47482bb294"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "acb7cfb8831ff9ebce0b8e7bfc3c02d43b83c8cd7f779e867f4ad31a6ab51576"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "belay"
  desc "AI-aware local version control for concurrent agent workflows"
  homepage "https://github.com/davidparkercodes/belay"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "belay"

  # No zap stanza required
end
