# This file was generated by GoReleaser. DO NOT EDIT.
cask "belay" do
  version "1.6.0"

  on_macos do
    on_arm do
      sha256 "0e08a6642c9fe5b6bc8ab861db877668b4b95f0ca67a6bb05a09b278788f9581"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8fe2733c90680e9827064f99bf4041fb1defde4c17fc842b021b3f9f092d83fe"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "67e50aaad388426346612fb3f482f64ba1155788aa8c4b4f59f4d5e42f5b0367"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "82dd6a67a8e4bb9ba2d19d9966dd5bdc95aae195a47aaba81530cc3b82045f66"
      url "https://github.com/davidparkercodes/belay/releases/download/v#{version}/belay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "belay"
  desc "AI-aware local version control for concurrent agent workflows"
  homepage "https://github.com/davidparkercodes/belay"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "belay"

  # No zap stanza required
end
